In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("C:/Users/DELL/Desktop/global cancer patients.csv")
df.head(2)

Patient_ID  Age Gender Country_Region  Year  Genetic_Risk  Air_Pollution  \
0  PT0000000   71   Male             UK  2021           6.4            2.8   
1  PT0000001   34   Male          China  2021           1.3            4.5   

   Alcohol_Use  Smoking  Obesity_Level Cancer_Type Cancer_Stage  \
0          9.5      0.9            8.7        Lung    Stage III   
1          3.7      3.9            6.3    Leukemia      Stage 0   

   Treatment_Cost_USD  Survival_Years  Target_Severity_Score  
0            62913.44             5.9                   4.92  
1            12573.41             4.7                   4.65

In [5]:
df.shape

(50000, 15)

In [7]:
df.isnull().sum()

Patient_ID               0
Age                      0
Gender                   0
Country_Region           0
Year                     0
Genetic_Risk             0
Air_Pollution            0
Alcohol_Use              0
Smoking                  0
Obesity_Level            0
Cancer_Type              0
Cancer_Stage             0
Treatment_Cost_USD       0
Survival_Years           0
Target_Severity_Score    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Patient_ID             50000 non-null  object 
 1   Age                    50000 non-null  int64  
 2   Gender                 50000 non-null  object 
 3   Country_Region         50000 non-null  object 
 4   Year                   50000 non-null  int64  
 5   Genetic_Risk           50000 non-null  float64
 6   Air_Pollution          50000 non-null  float64
 7   Alcohol_Use            50000 non-null  float64
 8   Smoking                50000 non-null  float64
 9   Obesity_Level          50000 non-null  float64
 10  Cancer_Type            50000 non-null  object 
 11  Cancer_Stage           50000 non-null  object 
 12  Treatment_Cost_USD     50000 non-null  float64
 13  Survival_Years         50000 non-null  float64
 14  Target_Severity_Score  50000 non-null  float64
dtypes:

In [11]:
df.describe()

Age          Year  Genetic_Risk  Air_Pollution   Alcohol_Use  \
count  50000.000000  50000.000000  50000.000000   50000.000000  50000.000000   
mean      54.421540   2019.480520      5.001698       5.010126      5.010880   
std       20.224451      2.871485      2.885773       2.888399      2.888769   
min       20.000000   2015.000000      0.000000       0.000000      0.000000   
25%       37.000000   2017.000000      2.500000       2.500000      2.500000   
50%       54.000000   2019.000000      5.000000       5.000000      5.000000   
75%       72.000000   2022.000000      7.500000       7.500000      7.500000   
max       89.000000   2024.000000     10.000000      10.000000     10.000000   

            Smoking  Obesity_Level  Treatment_Cost_USD  Survival_Years  \
count  50000.000000   50000.000000        50000.000000    50000.000000   
mean       4.989826       4.991176        52467.298239        5.006462   
std        2.881579       2.894504        27363.229379        2.883335   
min        0.000000       0.000000         5000.050000        0.000000   
25%        2.500000       2.500000        28686.225000        2.500000   
50%        5.000000       5.000000        52474.310000        5.000000   
75%        7.500000       7.500000        76232.720000        7.500000   
max       10.000000      10.000000        99999.840000       10.000000   

       Target_Severity_Score  
count           50000.000000  
mean                4.951207  
std                 1.199677  
min                 0.900000  
25%                 4.120000  
50%                 4.950000  
75%                 5.780000  
max                 9.160000

In [19]:
df['Country_Region'].value_counts().nunique()

9

In [21]:
df['Year'].value_counts().nunique()

10

In [23]:
df['Cancer_Type'].value_counts().nunique()

8

In [25]:
df['Cancer_Stage'].value_counts().nunique()

5

In [33]:
df=df.drop(columns=['Patient_ID','Age'],axis=1)

In [59]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [39]:
lab_enc=LabelEncoder()

In [43]:
df1=lab_enc.fit_transform(df['Gender'])
df['Gender']=df1
df1=lab_enc.fit_transform(df['Country_Region'])
df['Country_Region']=df1
df1=lab_enc.fit_transform(df['Year'])
df['Year']=df1
df1=lab_enc.fit_transform(df['Cancer_Stage'])
df['Cancer_Stage']=df1
df1=lab_enc.fit_transform(df['Cancer_Type'])
df['Cancer_Type']=df1

In [47]:
x=df.drop('Treatment_Cost_USD',axis=1)

In [49]:
y=df[['Treatment_Cost_USD']]

In [51]:
scaler=StandardScaler()

In [53]:
x_scaled = scaler.fit_transform(x)
x_scaled

array([[ 5.25217948e-03,  1.21126983e+00,  5.29167053e-01, ...,
         7.08735440e-01,  3.09900440e-01, -2.60134334e-02],
       [ 5.25217948e-03, -5.23695952e-01,  5.29167053e-01, ...,
        -1.41959921e+00, -1.06288382e-01, -2.51076304e-01],
       [ 5.25217948e-03,  5.17283518e-01,  1.22567777e+00, ...,
        -7.09444885e-04,  7.26089263e-01,  7.40867459e-01],
       ...,
       [ 5.25217948e-03,  5.17283518e-01, -1.56036510e+00, ...,
        -1.41959921e+00, -7.99936420e-01,  8.90909373e-01],
       [ 5.25217948e-03, -1.21768226e+00, -5.15599025e-01, ...,
         1.41818033e+00,  8.64818870e-01,  1.32436379e+00],
       [ 5.25217948e-03,  5.17283518e-01,  1.22567777e+00, ...,
        -1.41959921e+00,  8.30136468e-01, -9.92950211e-01]])

In [57]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size = 0.3 , random_state = 42)

In [61]:
ln = LinearRegression()

In [63]:
ln.fit(x_scaled,y)

LinearRegression()

In [65]:
y_predict = ln.predict(x_train)
y_predict

array([[15999.33127165],
       [97747.89439577],
       [76495.31796288],
       ...,
       [84251.21944625],
       [35499.69606053],
       [27745.65316508]])

In [67]:
x_predict = ln.predict(x_test)
x_predict

array([[ 5502.08034911],
       [61001.79116077],
       [62752.45763022],
       ...,
       [26999.68337137],
       [54750.82926661],
       [58000.33222195]])

In [69]:
r2_score(y_train,y_predict)

0.9999721663493077

In [71]:
r2_score(y_test,x_predict)

0.9999724716702713

In [83]:
from sklearn.tree import DecisionTreeRegressor

In [85]:
d_tree=DecisionTreeRegressor()

In [91]:
d_tree.fit(x_scaled,y)

DecisionTreeRegressor()

In [93]:
x_dtree=d_tree.predict(x_test)
x_dtree

array([ 5410.15, 61107.99, 62954.82, ..., 26889.81, 54637.42, 57791.73])

In [95]:
y_dtree=d_tree.predict(x_train)
y_dtree

array([15856.99, 97569.14, 76567.05, ..., 84450.46, 35354.69, 27750.62])

In [97]:
r2_score(y_train,y_dtree)

1.0

In [99]:
r2_score(y_test,x_dtree)

1.0