In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [2]:
d1=sns.load_dataset('tips')

In [3]:
d1

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
lab_enc=LabelEncoder()

In [5]:
d2=lab_enc.fit_transform(d1['sex'])

In [6]:
d1['sex']=d2

In [7]:
d1

total_bill   tip  sex smoker   day    time  size
0         16.99  1.01    0     No   Sun  Dinner     2
1         10.34  1.66    1     No   Sun  Dinner     3
2         21.01  3.50    1     No   Sun  Dinner     3
3         23.68  3.31    1     No   Sun  Dinner     2
4         24.59  3.61    0     No   Sun  Dinner     4
..          ...   ...  ...    ...   ...     ...   ...
239       29.03  5.92    1     No   Sat  Dinner     3
240       27.18  2.00    0    Yes   Sat  Dinner     2
241       22.67  2.00    1    Yes   Sat  Dinner     2
242       17.82  1.75    1     No   Sat  Dinner     2
243       18.78  3.00    0     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
d2=lab_enc.fit_transform(d1['smoker'])
d1['smoker']=d2
d2=lab_enc.fit_transform(d1['time'])
d1['time']=d2
d2=lab_enc.fit_transform(d1['day'])
d1['day']=d2

In [9]:
d1

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]

In [10]:
x = d1.drop('total_bill',axis = 1)

In [11]:
y = d1[['total_bill']]

In [12]:
scaler = StandardScaler()

In [13]:
x_scaled = scaler.fit_transform(x)
x_scaled

array([[-1.43994695e+00, -1.34335316e+00, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01, -6.00192629e-01],
       [-9.69205340e-01,  7.44405889e-01, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       [ 3.63355539e-01,  7.44405889e-01, -7.84789169e-01,
         2.79157595e-01, -6.21581561e-01,  4.53382921e-01],
       ...,
       [-7.22971264e-01,  7.44405889e-01,  1.27422758e+00,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [-9.04025732e-01,  7.44405889e-01, -7.84789169e-01,
        -8.02024201e-01, -6.21581561e-01, -6.00192629e-01],
       [ 1.24660453e-03, -1.34335316e+00, -7.84789169e-01,
         1.36033939e+00, -6.21581561e-01, -6.00192629e-01]])

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x_scaled,y,test_size = 0.3 , random_state = 42)

In [18]:
ln = LinearRegression()

In [19]:
ln.fit(x_scaled,y)

LinearRegression()

In [20]:
y_predict = ln.predict(x_train)
y_predict

array([[19.99708257],
       [24.30469965],
       [29.29620971],
       [29.97424715],
       [26.814367  ],
       [32.73416301],
       [12.46201407],
       [23.36153334],
       [21.36028629],
       [10.74347481],
       [26.814367  ],
       [17.17181531],
       [22.75727014],
       [13.43910541],
       [22.75297285],
       [21.51073195],
       [18.05044534],
       [29.93304577],
       [11.68829931],
       [22.63633903],
       [19.36769946],
       [15.62008851],
       [31.79113452],
       [16.93319284],
       [21.99701139],
       [20.24467129],
       [16.44111865],
       [19.83950808],
       [17.66238981],
       [16.39248502],
       [13.21936202],
       [14.3925562 ],
       [12.07141194],
       [17.44293137],
       [38.02371214],
       [15.86919053],
       [10.69926267],
       [22.82082552],
       [26.30462847],
       [24.05447184],
       [17.06559279],
       [12.29090432],
       [11.14580648],
       [20.71485564],
       [19.61974399],
       [28

In [21]:
x_predict = ln.predict(x_test)
x_predict

array([[18.04448985],
       [14.76989478],
       [21.58717921],
       [33.49926248],
       [14.80057166],
       [17.27956213],
       [17.5404144 ],
       [13.90023101],
       [18.57657138],
       [18.6130223 ],
       [17.8647538 ],
       [12.75228092],
       [10.74347481],
       [17.27956213],
       [ 8.35613607],
       [13.71883676],
       [25.4056536 ],
       [20.7120241 ],
       [14.84041825],
       [32.8081297 ],
       [21.5958055 ],
       [21.97925809],
       [22.0852199 ],
       [12.69038374],
       [24.32377118],
       [14.2570323 ],
       [13.87238567],
       [25.18007892],
       [21.58717921],
       [37.68904069],
       [24.36825503],
       [15.1691025 ],
       [22.2620927 ],
       [20.64700296],
       [21.81410383],
       [21.95545904],
       [14.97745546],
       [30.90243314],
       [14.61204858],
       [16.90222355],
       [12.07141194],
       [12.29090432],
       [16.47206724],
       [16.15051183],
       [15.80729335],
       [ 9

In [22]:
#overFitting and underfitting

In [23]:
r2_score(y_train,y_predict)

0.5623955024259775

In [24]:
r2_score(y_test,x_predict)

0.60719822452258

In [25]:
mean_absolute_error(y_test,x_predict)

3.9048059824905366

In [26]:
mean_squared_error(y_test,x_predict)

27.361130191926673